stages:
  - build
  - deploy

build site:
  image: node:latest
  stage: build
  tags:
    - gitlab-org
  script:
    - yarn install
    - yarn upgrade
    - yarn run build
  artifacts:
    expire_in: 1 day
    paths:
      - dist

deploy:
  image: alpine
  stage: deploy
  tags:
    - gitlab-org
  script:
    - apk add --no-cache rsync openssh
    - mkdir -p ~/.ssh
    - echo "$SSH_PRIVATE_KEY" >> ~/.ssh/id_dsa
    - chmod 600 ~/.ssh/id_dsa
    - echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config
    - rsync -rav --delete dist/ $WATSINA_HOME
  when: manual
  only:
    - master
